#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           7
bspc config top_padding		30

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

##Desktop Rules

# Files Desktop 2
bspc rule -a Thunar desktop='^2' follow=on

# Internet Desktop 3
bspc rule -a firefox desktop='^3' follow=on
bspc rule -a Chromium desktop='^3'

# Games Desktop 4
bspc rule -a Steam desktop='^4'
bspc rule -a heroic desktop='^4'
bspc rule -a Lutris desktop='^4'
bspc rule -a yuzu desktop='^4'

# VoIP Desktop 5
bspc rule -a discord desktop='^5'
bspc rule -a zoom desktop='^5'
bspc rule -a Element desktop='^5'

# Code Desktop 6
bspc rule -a Code desktop='^6' follow=on
bspc rule -a jetbrains-idea-ce desktop='^6' follow=on
bspc rule -a Eclipse desktop='^6' follow=on

# System Desktop 7
bspc rule -a helvum desktop='^7' follow=on
bspc rule -a Yad desktop='^7' state=floating

# Graphic Design Desktop 8
bspc rule -a "Gimp-2.10" desktop='^8' follow=on
bspc rule -a Inkscape desktop='^8' follow=on
bspc rule -a krita desktop='^8' follow=on

# Multimedia Desktop 9
bspc rule -a firefox:Toolkit desktop='^9' follow=on
bspc rule -a mpv desktop='^9' follow=on 
bspc rule -a hyperbeam desktop='^9' follow=on 

# Music Desktop 0
bspc rule -a "Nuclear Music Player" desktop='^0' follow=off

# Miscellaneous Rules 
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Pavucontrol state=floating rectangle=526x350+0+0 center=true
bspc rule -a PureRef state=floating
bspc rule -a Emacs state=tiled
bspc rule -a balena-etcher-electron state=tiled
bspc rule -a Pycalendar.py state=floating rectangle=550x250+800+40
bspc rule -a "Select Font" state=tiled
bspc rule -a MEGAsync state=floating rectangle=250x400+950+40

## Border
bspc config focused_border_color        "#bd93f9"
bspc config normal_border_color         "#282a36"
bspc config active_border_color         "#44475a"

bspc config presel_feedback_color       "#bd93f9"

#Run single instance
function runSingle() {
  local program=$1

  ps_result=$(ps aux \
    | grep "${program}" \
    | grep -v "grep" \
    | wc -l 
    )
  if [ $ps_result -eq 0 ]; then
    `$program` &
 else
    echo "$program already running"
  fi
}

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
picom -b --experimental-backends &
# Cursor
xsetroot -cursor_name left_ptr &
#keyring
eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK


##System tray icons
# Network Applet
nm-applet --indicator &
# Bluetooth
blueman-applet &
# Firewall Applet
# runSingle firewall-applet
# Battery
runSingle cbatticon
#Volume icon
#runSingle volctl
#Redshift
#runSingle redshift

# Audio Sink Loopback
#killall pw-loopback
#pw-loopback -m '[ FL FR]' --capture-props='media.class=Audio/Sink node.name=my-sink' &
#sleep .5s 
#pactl set-sink-volume my-sink 20%

# Low battery notifier
#~/.config/bspwm/scripts/low_bat_notifier.sh

#Spotify Fix
#~/.config/bspwm/scripts/spotify-rule.sh
#Jetbrains fix 
#wmname LG3D
